; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = upesy_wroom
framework = arduino

; ------------------------------------------------------------------
; LUVA DIREITA  ->  envia UDP broadcast na porta 4210
; (casa com imu.py: IMU_PORTAS_PADRAO = {1: 4210, 2: 4211}, lado 1 = direita)
; ------------------------------------------------------------------
[env:luva_direita]
build_flags = -D GLOVE_SIDE=1

; ------------------------------------------------------------------
; LUVA ESQUERDA ->  envia UDP broadcast na porta 4211
; ------------------------------------------------------------------
[env:luva_esquerda]
build_flags = -D GLOVE_SIDE=0
